import { createTypes } from 'reduxsauce';

export default createTypes(`
  SET_FEED_NAVIGATOR
  SET_INSIGHT_NAVIGATOR
  SET_POST_NAVIGATOR
  SET_SCHEDULE_NAVIGATOR
  SET_SETTINGS_NAVIGATOR
  SET_APP_NAVIGATOR
  SET_MAIN_NAVIGATOR     
  
  SET_DEVICE_TOKEN
  SET_USER_INFO
  UPDATE_USER_INFO
  OPEN_DRAWER
  CLOSE_DRAWER

  SET_DATA
  SET_TIME_LIMIT
  
  PUSH_NEW_ROUTE
  REPLACE_ROUTE
  REPLACE_OR_PUSH_ROUTE
  POP_ROUTE
  POP_TO_ROUTE
  LOAD_TASKS_REQUEST
  LOAD_TASKS_ERROR
  LOAD_TASKS_SUCCESS 
  SET_HOME_TAB 
  SET_SPINNER_VISIBLE
  SELECT_TOPIC
  SELECT_TOPICS
`);